fix: build and secrets

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,10 +1,14 @@
 on:
   schedule:
-    - cron: '*/15 * * * *'
+    - cron: "*/15 * * * *"
 
 jobs:
   test_schedule:
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            curl -H "CRON_API_SECRET: ${CRON_API_SECRET}" "https://smartriver.top/api/cron"
+      - run: |
+          export STATUS=$(curl -s -o /dev/null -w "%{http_code}" -H "authorization: ${CRON_API_SECRET}" "https://smartriver.top/api/cron")
+          if [[ "$STATUS" ne "200" ]]; then
+            echo "Error contacting api/cron $STATUS";
+            exit 1;
+          fi
